const timeZones = [
    { offset: "UTC+05:30", location: "Chennai, Kolkata, Mumbai, New Delhi" },
    { offset: "UTC-12:00", location: "Baker Island, Howland Island" },
    { offset: "UTC-11:00", location: "American Samoa, Niue" },
    { offset: "UTC-10:00", location: "Hawaii, Tahiti" },
    { offset: "UTC-09:30", location: "Marquesas Islands" },
    { offset: "UTC-09:00", location: "Alaska" },
    { offset: "UTC-08:00", location: "Pacific Time (US & Canada), Baja California" },
    { offset: "UTC-07:00", location: "Mountain Time (US & Canada), Chihuahua, La Paz, Mazatlan" },
    { offset: "UTC-06:00", location: "Central Time (US & Canada), Central America, Mexico City" },
    { offset: "UTC-05:00", location: "Eastern Time (US & Canada), Bogota, Lima" },
    { offset: "UTC-04:30", location: "Caracas" },
    { offset: "UTC-04:00", location: "Atlantic Time (Canada), Manaus, Santiago" },
    { offset: "UTC-03:30", location: "Newfoundland" },
    { offset: "UTC-03:00", location: "Brasilia, Buenos Aires, Greenland" },
    { offset: "UTC-02:00", location: "Mid+Atlantic" },
    { offset: "UTC-01:00", location: "Azores, Cape Verde" },
    { offset: "UTC+00:00", location: "Dublin, London, Lisbon, Casablanca" },
    { offset: "UTC+01:00", location: "Central European Time, West Africa Time" },
    { offset: "UTC+02:00", location: "Eastern European Time, Cairo, Johannesburg" },
    { offset: "UTC+03:00", location: "Moscow, Istanbul, Baghdad" },
    { offset: "UTC+03:30", location: "Tehran" },
    { offset: "UTC+04:00", location: "Samara, Abu Dhabi, Muscat" },
    { offset: "UTC+04:30", location: "Kabul" },
    { offset: "UTC+05:00", location: "Ekaterinburg, Islamabad, Karachi" },

    { offset: "UTC+05:45", location: "Kathmandu" },
    { offset: "UTC+06:00", location: "Astana, Dhaka, Novosibirsk" },
    { offset: "UTC+06:30", location: "Yangon" },
    { offset: "UTC+07:00", location: "Bangkok, Hanoi, Jakarta" },
    { offset: "UTC+08:00", location: "Beijing, Hong Kong, Singapore" },
    { offset: "UTC+08:45", location: "Eucla" },
    { offset: "UTC+09:00", location: "Tokyo, Seoul, Yakutsk" },
    { offset: "UTC+09:30", location: "Adelaide, Darwin" },
    { offset: "UTC+10:00", location: "Eastern Australia, Guam, Vladivostok" },
    { offset: "UTC+10:30", location: "Lord Howe Island" },
    { offset: "UTC+11:00", location: "Magadan, Solomon Islands, Vanuatu" },
    { offset: "UTC+11:30", location: "Norfolk Island" },
    { offset: "UTC+12:00", location: "Auckland, Fiji, Kamchatka" },
    { offset: "UTC+12:45", location: "Chatham Islands" },
    { offset: "UTC+13:00", location: "Tongatapu, Phoenix Islands" },
    { offset: "UTC+14:00", location: "Line Islands" }
];

export default timeZones;
